# Regression With Keras C

## Table of content

1. Data Viualization
2. Data preprocessing
3.Model Building
4.Model Training
5.Model Evaluation
6.MSE mean and std calculation

Data Cleaning and preprocessing

Importing the required Libraries

In [1]:
import numpy as np
import pandas as pd
from keras.models import Sequential
from keras.layers import Dense
from sklearn.model_selection import train_test_split

Using TensorFlow backend.
/home/jupyterlab/conda/envs/python/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:519: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/home/jupyterlab/conda/envs/python/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:520: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/home/jupyterlab/conda/envs/python/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:521: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/home/jupyterlab/conda/envs/python/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:522: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/home/jupyterlab/conda/envs/python/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:523: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/home/jupyterlab/conda/envs/python/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:528: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])

Dataset Loading

In [2]:
data=pd.read_csv("concrete_data.csv")
data.head()

,Cement,Blast Furnace Slag,Fly Ash,Water,Superplasticizer,Coarse Aggregate,Fine Aggregate,Age,Strength
0,540.0,0.0,0.0,162.0,2.5,1040.0,676.0,28,79.99
1,540.0,0.0,0.0,162.0,2.5,1055.0,676.0,28,61.89
2,332.5,142.5,0.0,228.0,0.0,932.0,594.0,270,40.27
3,332.5,142.5,0.0,228.0,0.0,932.0,594.0,365,41.05
4,198.6,132.4,0.0,192.0,0.0,978.4,825.5,360,44.30

In [3]:
data.shape

(1030, 9)

In [4]:
data.describe()

,Cement,Blast Furnace Slag,Fly Ash,Water,Superplasticizer,Coarse Aggregate,Fine Aggregate,Age,Strength
count,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000
mean,281.167864,73.895825,54.188350,181.567282,6.204660,972.918932,773.580485,45.662136,35.817961
std,104.506364,86.279342,63.997004,21.354219,5.973841,77.753954,80.175980,63.169912,16.705742
min,102.000000,0.000000,0.000000,121.800000,0.000000,801.000000,594.000000,1.000000,2.330000
25%,192.375000,0.000000,0.000000,164.900000,0.000000,932.000000,730.950000,7.000000,23.710000
50%,272.900000,22.000000,0.000000,185.000000,6.400000,968.000000,779.500000,28.000000,34.445000
75%,350.000000,142.950000,118.300000,192.000000,10.200000,1029.400000,824.000000,56.000000,46.135000
max,540.000000,359.400000,200.100000,247.000000,32.200000,1145.000000,992.600000,365.000000,82.600000

Checking for null values

In [5]:
data.isnull().sum()

Cement                0
Blast Furnace Slag    0
Fly Ash               0
Water                 0
Superplasticizer      0
Coarse Aggregate      0
Fine Aggregate        0
Age                   0
Strength              0
dtype: int64

Spliting the dataset into predicting variables and target ones

In [6]:
target_variables=data["Strength"]
predicting_variables=data[["Cement","Blast Furnace Slag", "Fly Ash","Water",
                         "Superplasticizer", "Coarse Aggregate", "Fine Aggregate", "Age"]]
predicting_variables.head()

,Cement,Blast Furnace Slag,Fly Ash,Water,Superplasticizer,Coarse Aggregate,Fine Aggregate,Age
0,540.0,0.0,0.0,162.0,2.5,1040.0,676.0,28
1,540.0,0.0,0.0,162.0,2.5,1055.0,676.0,28
2,332.5,142.5,0.0,228.0,0.0,932.0,594.0,270
3,332.5,142.5,0.0,228.0,0.0,932.0,594.0,365
4,198.6,132.4,0.0,192.0,0.0,978.4,825.5,360

In [7]:
target_variables.head()

0    79.99
1    61.89
2    40.27
3    41.05
4    44.30
Name: Strength, dtype: float64

Normalization for predicting variables

In [8]:
predicting_val=(predicting_variables-predicting_variables.mean())/predicting_variables.std()
predicting_val.head()

,Cement,Blast Furnace Slag,Fly Ash,Water,Superplasticizer,Coarse Aggregate,Fine Aggregate,Age
0,2.476712,-0.856472,-0.846733,-0.916319,-0.620147,0.862735,-1.217079,-0.279597
1,2.476712,-0.856472,-0.846733,-0.916319,-0.620147,1.055651,-1.217079,-0.279597
2,0.491187,0.795140,-0.846733,2.174405,-1.038638,-0.526262,-2.239829,3.551340
3,0.491187,0.795140,-0.846733,2.174405,-1.038638,-0.526262,-2.239829,5.055221
4,-0.790075,0.678079,-0.846733,0.488555,-1.038638,0.070492,0.647569,4.976069

Creating ncols as we are going to need it in building our model

In [9]:
ncols=predicting_val.shape[1]

### Now we are good to build our model

As we've imorted all required libraries at the top we are going to build our model

Defining the model function

In [10]:
def regression_model():
    
    #Build the model
    model=Sequential()
    model.add(Dense(10,activation="relu", input_shape=(ncols,)))
    model.add(Dense(1))
    
    #compile the model
    model.compile(optimizer='adam', loss='mean_squared_error')
    return model

Training the Model

In [11]:
model=regression_model()

In [12]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split( predicting_val, target_variables, test_size=0.3, random_state=4)
print ('Train set:', X_train.shape,  y_train.shape)
print ('Test set:', X_test.shape,  y_test.shape)
# fit the model
model.fit(predicting_val, target_variables, validation_split=0.3, epochs=100, verbose=1)

Train set: (721, 8) (721,)
Test set: (309, 8) (309,)
Train on 721 samples, validate on 309 samples
Epoch 1/100
721/721 [==============================] - 1s 833us/step - loss: 1738.0375 - val_loss: 1241.6273
Epoch 2/100
721/721 [==============================] - 0s 314us/step - loss: 1719.2123 - val_loss: 1229.2188
Epoch 3/100
721/721 [==============================] - 0s 305us/step - loss: 1701.1820 - val_loss: 1216.9555
Epoch 4/100
721/721 [==============================] - 0s 361us/step - loss: 1683.2107 - val_loss: 1204.9521
Epoch 5/100
721/721 [==============================] - 0s 418us/step - loss: 1664.9753 - val_loss: 1192.7845
Epoch 6/100
721/721 [==============================] - 0s 385us/step - loss: 1646.2136 - val_loss: 1180.2742
Epoch 7/100
721/721 [==============================] - 0s 387us/step - loss: 1626.4419 - val_loss: 1167.3438
Epoch 8/100
721/721 [==============================] - 0s 354us/step - loss: 1605.6873 - val_loss: 1153.3603
Epoch 9/100
721/721 [==============================] - 0s 336us/step - loss: 1583.8020 - val_loss: 1138.9988
Epoch 10/100
721/721 [==============================] - 0s 396us/step - loss: 1560.5723 - val_loss: 1123.6097
Epoch 11/100
721/721 [==============================] - 0s 572us/step - loss: 1535.5045 - val_loss: 1107.5323
Epoch 12/100
721/721 [==============================] - 0s 336us/step - loss: 1509.3987 - val_loss: 1090.2370
Epoch 13/100
721/721 [==============================] - 0s 413us/step - loss: 1481.1919 - val_loss: 1072.5984
Epoch 14/100
721/721 [==============================] - 0s 445us/step - loss: 1451.9271 - val_loss: 1054.0094
Epoch 15/100
721/721 [==============================] - 0s 518us/step - loss: 1421.2912 - val_loss: 1034.5955
Epoch 16/100
721/721 [==============================] - 0s 361us/step - loss: 1388.5786 - val_loss: 1014.3204
Epoch 17/100
721/721 [==============================] - 0s 437us/step - loss: 1354.7768 - val_loss: 993.5382
Epoch 18/100
721/721 [==============================] - 0s 388us/step - loss: 1320.2790 - val_loss: 971.3895
Epoch 19/100
721/721 [==============================] - 0s 361us/step - loss: 1284.1151 - val_loss: 949.5377
Epoch 20/100
721/721 [==============================] - 0s 387us/step - loss: 1247.4363 - val_loss: 926.7434
Epoch 21/100
721/721 [==============================] - 0s 449us/step - loss: 1210.4432 - val_loss: 903.4021
Epoch 22/100
721/721 [==============================] - 0s 299us/step - loss: 1172.1549 - val_loss: 880.4934
Epoch 23/100
721/721 [==============================] - 0s 357us/step - loss: 1134.1718 - val_loss: 857.1611
Epoch 24/100
721/721 [==============================] - 0s 387us/step - loss: 1095.7613 - val_loss: 833.7429
Epoch 25/100
721/721 [==============================] - 0s 380us/step - loss: 1057.0006 - val_loss: 810.2819
Epoch 26/100
721/721 [==============================] - 0s 361us/step - loss: 1018.5430 - val_loss: 787.1387
Epoch 27/100
721/721 [==============================] - 0s 305us/step - loss: 980.2541 - val_loss: 763.8933
Epoch 28/100
721/721 [==============================] - 0s 494us/step - loss: 942.1055 - val_loss: 740.6939
Epoch 29/100
721/721 [==============================] - 0s 561us/step - loss: 904.5348 - val_loss: 717.5220
Epoch 30/100
721/721 [==============================] - 0s 295us/step - loss: 867.6011 - val_loss: 695.4833
Epoch 31/100
721/721 [==============================] - 0s 322us/step - loss: 831.7635 - val_loss: 672.9934
Epoch 32/100
721/721 [==============================] - 0s 318us/step - loss: 796.5948 - val_loss: 651.5716
Epoch 33/100
721/721 [==============================] - 0s 385us/step - loss: 762.1214 - val_loss: 630.5216
Epoch 34/100
721/721 [==============================] - 0s 332us/step - loss: 728.5748 - val_loss: 610.1919
Epoch 35/100
721/721 [==============================] - 0s 441us/step - loss: 696.7940 - val_loss: 589.8445
Epoch 36/100
721/721 [==============================] - 0s 336us/step - loss: 665.2417 - val_loss: 569.9943
Epoch 37/100
721/721 [==============================] - 0s 388us/step - loss: 635.3404 - val_loss: 551.2902
Epoch 38/100
721/721 [==============================] - 0s 379us/step - loss: 606.6789 - val_loss: 533.5293
Epoch 39/100
721/721 [==============================] - 0s 355us/step - loss: 579.1751 - val_loss: 516.1688
Epoch 40/100
721/721 [==============================] - 0s 311us/step - loss: 553.1953 - val_loss: 499.2410
Epoch 41/100
721/721 [==============================] - 0s 325us/step - loss: 528.5960 - val_loss: 483.1830
Epoch 42/100
721/721 [==============================] - 0s 476us/step - loss: 504.8978 - val_loss: 468.0635
Epoch 43/100
721/721 [==============================] - 0s 437us/step - loss: 482.9381 - val_loss: 453.5615
Epoch 44/100
721/721 [==============================] - 0s 391us/step - loss: 462.2884 - val_loss: 439.5883
Epoch 45/100
721/721 [==============================] - 0s 363us/step - loss: 442.5918 - val_loss: 426.2474
Epoch 46/100
721/721 [==============================] - 0s 311us/step - loss: 424.2447 - val_loss: 413.8693
Epoch 47/100
721/721 [==============================] - 0s 509us/step - loss: 407.0533 - val_loss: 401.8052
Epoch 48/100
721/721 [==============================] - 0s 389us/step - loss: 391.0660 - val_loss: 390.6442
Epoch 49/100
721/721 [==============================] - 0s 417us/step - loss: 376.3145 - val_loss: 379.3119
Epoch 50/100
721/721 [==============================] - 0s 328us/step - loss: 362.4800 - val_loss: 369.7586
Epoch 51/100
721/721 [==============================] - 0s 287us/step - loss: 350.0482 - val_loss: 360.3125
Epoch 52/100
721/721 [==============================] - 0s 350us/step - loss: 338.3050 - val_loss: 351.3887
Epoch 53/100
721/721 [==============================] - 0s 334us/step - loss: 327.4617 - val_loss: 343.6455
Epoch 54/100
721/721 [==============================] - 0s 345us/step - loss: 317.5587 - val_loss: 335.9751
Epoch 55/100
721/721 [==============================] - 0s 353us/step - loss: 308.4783 - val_loss: 328.2492
Epoch 56/100
721/721 [==============================] - 0s 330us/step - loss: 300.1219 - val_loss: 321.6305
Epoch 57/100
721/721 [==============================] - 0s 638us/step - loss: 292.2977 - val_loss: 314.8876
Epoch 58/100
721/721 [==============================] - 0s 315us/step - loss: 285.1716 - val_loss: 308.7282
Epoch 59/100
721/721 [==============================] - 0s 357us/step - loss: 278.5217 - val_loss: 303.6770
Epoch 60/100
721/721 [==============================] - 0s 381us/step - loss: 272.5959 - val_loss: 298.7319
Epoch 61/100
721/721 [==============================] - 0s 421us/step - loss: 267.0396 - val_loss: 293.3709
Epoch 62/100
721/721 [==============================] - 0s 360us/step - loss: 261.8077 - val_loss: 288.8834
Epoch 63/100
721/721 [==============================] - 0s 381us/step - loss: 257.2198 - val_loss: 285.0522
Epoch 64/100
721/721 [==============================] - 0s 339us/step - loss: 252.9758 - val_loss: 280.9553
Epoch 65/100
721/721 [==============================] - 0s 299us/step - loss: 249.0249 - val_loss: 277.8293
Epoch 66/100
721/721 [==============================] - 0s 331us/step - loss: 245.1842 - val_loss: 274.5998
Epoch 67/100
721/721 [==============================] - 0s 332us/step - loss: 241.8900 - val_loss: 271.2571
Epoch 68/100
721/721 [==============================] - 0s 334us/step - loss: 238.6956 - val_loss: 268.1247
Epoch 69/100
721/721 [==============================] - 0s 468us/step - loss: 235.6723 - val_loss: 266.1045
Epoch 70/100
721/721 [==============================] - 0s 363us/step - loss: 232.9646 - val_loss: 263.6585
Epoch 71/100
721/721 [==============================] - 0s 393us/step - loss: 230.3074 - val_loss: 261.5412
Epoch 72/100
721/721 [==============================] - 0s 360us/step - loss: 227.8442 - val_loss: 259.2549
Epoch 73/100
721/721 [==============================] - 0s 356us/step - loss: 225.6484 - val_loss: 257.2916
Epoch 74/100
721/721 [==============================] - 0s 358us/step - loss: 223.3348 - val_loss: 255.8741
Epoch 75/100
721/721 [==============================] - 0s 381us/step - loss: 221.3220 - val_loss: 253.8539
Epoch 76/100
721/721 [==============================] - 0s 448us/step - loss: 219.3996 - val_loss: 252.3410
Epoch 77/100
721/721 [==============================] - 0s 411us/step - loss: 217.6667 - val_loss: 251.0561
Epoch 78/100
721/721 [==============================] - 0s 383us/step - loss: 215.8456 - val_loss: 249.6533
Epoch 79/100
721/721 [==============================] - 0s 557us/step - loss: 214.0908 - val_loss: 248.5815
Epoch 80/100
721/721 [==============================] - 0s 360us/step - loss: 212.5832 - val_loss: 247.6454
Epoch 81/100
721/721 [==============================] - 0s 392us/step - loss: 211.1132 - val_loss: 246.0426
Epoch 82/100
721/721 [==============================] - 0s 631us/step - loss: 209.5985 - val_loss: 245.1191
Epoch 83/100
721/721 [==============================] - 0s 388us/step - loss: 208.2508 - val_loss: 244.2672
Epoch 84/100
721/721 [==============================] - 0s 357us/step - loss: 206.8795 - val_loss: 243.2153
Epoch 85/100
721/721 [==============================] - 0s 329us/step - loss: 205.6504 - val_loss: 242.7623
Epoch 86/100
721/721 [==============================] - 0s 339us/step - loss: 204.3281 - val_loss: 241.9436
Epoch 87/100
721/721 [==============================] - 0s 384us/step - loss: 203.1892 - val_loss: 240.4512
Epoch 88/100
721/721 [==============================] - 0s 360us/step - loss: 201.9788 - val_loss: 240.0114
Epoch 89/100
721/721 [==============================] - 0s 329us/step - loss: 200.7955 - val_loss: 239.3302
Epoch 90/100
721/721 [==============================] - 0s 476us/step - loss: 199.6451 - val_loss: 238.8693
Epoch 91/100
721/721 [==============================] - 1s 757us/step - loss: 198.6305 - val_loss: 237.7841
Epoch 92/100
721/721 [==============================] - 0s 339us/step - loss: 197.6211 - val_loss: 237.2387
Epoch 93/100
721/721 [==============================] - 0s 407us/step - loss: 196.5505 - val_loss: 236.5284
Epoch 94/100
721/721 [==============================] - 0s 499us/step - loss: 195.5804 - val_loss: 235.5926
Epoch 95/100
721/721 [==============================] - 0s 307us/step - loss: 194.6016 - val_loss: 234.6392
Epoch 96/100
721/721 [==============================] - 0s 450us/step - loss: 193.6977 - val_loss: 234.0456
Epoch 97/100
721/721 [==============================] - 0s 402us/step - loss: 192.7195 - val_loss: 233.2367
Epoch 98/100
721/721 [==============================] - 0s 333us/step - loss: 191.8387 - val_loss: 232.3011
Epoch 99/100
721/721 [==============================] - 0s 331us/step - loss: 190.9011 - val_loss: 231.7086
Epoch 100/100
721/721 [==============================] - 0s 392us/step - loss: 190.1236 - val_loss: 231.3000

In [13]:
loss_val = model.evaluate(X_test, y_test)
yhat = model.predict(X_test)
loss_val

309/309 [==============================] - 0s 188us/step

211.99146974433972

Model Evaluation

In [14]:

from sklearn.metrics import mean_squared_error
#Mean and std calculation for mse
mse = mean_squared_error(y_test, yhat)
mean = np.mean(mse)
standard_deviation = np.std(mse)
print("Mean of mse is: ",mean,"and STD of mse is: ", standard_deviation)

Mean of mse is:  211.99146895211265 and STD of mse is:  0.0

In [15]:
total_errors = 100
epochs = 100
mean_squared_errors = []
for i in range(0, total_errors):
    X_train, X_test, y_train, y_test = train_test_split(predicting_val, target_variables, test_size=0.3, random_state=i)
    model.fit(X_train, y_train, epochs=epochs, verbose=0)
    MSE = model.evaluate(X_test, y_test, verbose=0)
    print("MSE "+str(i+1)+": "+str(MSE))
    yhat = model.predict(X_test)
    mean_square_error = mean_squared_error(y_test, yhat)
    mean_squared_errors.append(mean_square_error)

mean_squared_errors = np.array(mean_squared_errors)
mean = np.mean(mean_squared_errors)
standard_deviation = np.std(mean_squared_errors)

print('\n')
print("Below is the mean and standard deviation of " +str(total_errors) + " mean squared errors without normalized data. Total number of epochs is: " +str(epochs) + "\n")
print("Mean: "+str(mean))
print("Standard Deviation: "+str(standard_deviation))

MSE 1: 81.76896152681518
MSE 2: 62.31105192116549
MSE 3: 41.394909121072025
MSE 4: 39.475935976096345
MSE 5: 37.35295692616682
MSE 6: 39.67595122007105
MSE 7: 41.53004428406749
MSE 8: 34.88612473126754
MSE 9: 34.24771337910377
MSE 10: 35.03224991980494
MSE 11: 32.59631336545481
MSE 12: 30.560622360328253
MSE 13: 35.62612612579247
MSE 14: 39.940565683309316
MSE 15: 32.967641237870005
MSE 16: 27.040839185992493
MSE 17: 30.04203487136989
MSE 18: 31.52450170177472
MSE 19: 29.32664760108133
MSE 20: 32.71678910980719
MSE 21: 29.9154316059594
MSE 22: 29.96202110858411
MSE 23: 26.37049841649324
MSE 24: 26.977912668271358
MSE 25: 31.806002447134468
MSE 26: 31.36701590034954
MSE 27: 25.53484222881231
MSE 28: 28.445010435233996
MSE 29: 31.37009284874382
MSE 30: 25.83755306132789
MSE 31: 26.712838243898066
MSE 32: 25.702915957058902
MSE 33: 27.009268973637553
MSE 34: 27.834109766197823
MSE 35: 30.11873789666926
MSE 36: 32.755912527683094
MSE 37: 25.267598013276036
MSE 38: 30.489786907307153
MSE 39: 28.28539580434657
MSE 40: 26.24630752119046
MSE 41: 29.625270880541756
MSE 42: 24.945428187793127
MSE 43: 29.04308846236047
MSE 44: 30.547529510695572
MSE 45: 32.714106562839746
MSE 46: 29.48295677209749
MSE 47: 26.76007108472312
MSE 48: 31.058359028837828
MSE 49: 26.513111447825015
MSE 50: 29.19156829438935
MSE 51: 25.735958333925907
MSE 52: 28.973972888440375
MSE 53: 27.616568938813934
MSE 54: 26.707413127121416
MSE 55: 34.23055557448502
MSE 56: 27.51460409318745
MSE 57: 27.560449248378717
MSE 58: 26.53533617038171
MSE 59: 27.826277890251678
MSE 60: 31.1806166442081
MSE 61: 30.584692347011135
MSE 62: 25.24325748554711
MSE 63: 27.532300646636862
MSE 64: 28.332416373934947
MSE 65: 26.07994624017512
MSE 66: 27.59485083027565
MSE 67: 25.243831622176184
MSE 68: 28.824344807843946
MSE 69: 25.189561016737066
MSE 70: 25.77905439481766
MSE 71: 25.38991662059401
MSE 72: 26.427791033747898
MSE 73: 25.34547709492804
MSE 74: 26.77385096874052
MSE 75: 28.682627767420897
MSE 76: 27.583602571950376
MSE 77: 24.36150412574941
MSE 78: 27.21749996444554
MSE 79: 27.98289046549874
MSE 80: 29.57895409790829
MSE 81: 25.477705514160945
MSE 82: 28.528090529457266
MSE 83: 28.46881955341228
MSE 84: 24.37491479892175
MSE 85: 26.170555904845205
MSE 86: 27.5264132910176
MSE 87: 27.299005675084384
MSE 88: 28.823955498852776
MSE 89: 27.470698600448067
MSE 90: 29.568736011542164
MSE 91: 29.31753010425753
MSE 92: 26.652207769622308
MSE 93: 27.4884454918525
MSE 94: 27.977586079569697
MSE 95: 29.740567537573163
MSE 96: 26.835000942440093
MSE 97: 27.00585525167027
MSE 98: 26.113503619690928
MSE 99: 29.09691143344521
MSE 100: 25.402882474140057


Below is the mean and standard deviation of 100 mean squared errors without normalized data. Total number of epochs is: 100

Mean: 30.008782181143815
Standard Deviation: 7.1868297719589105

The Mean of B i greater compared to Mean of C